### ISSUE TITLE
xeffyr/termux no longer on dockerhub

### ISSUE THREAD

**Issue by guijan** [termux/termux-docker#18]
Hi, it seems the docker image is no longer available on docker hub: https://hub.docker.com/r/xeffyr/termux

The image is really good for CI because it's a Linux system with the bionic libc, it's very straightforward to use and works well, unlike Google's NDK. I use it in [my current project](https://github.com/guijan/libobsd).

It would be really nice if this image could be on docker hub again.

**Comment by kcubeterm** [comment]
please consider to use kcubeterm/termux:latest image
