### ISSUE TITLE
The error when using Podman on ARM64 VPS

### ISSUE THREAD

**Issue by txmu** [termux/termux-docker#26]
When I tried to use an ARM64 VPS (using podman), 

`$ sudo ./build-all.sh --podman`

an error appeared:

![IMG_20220426_161828](https://user-images.githubusercontent.com/71213934/165255235-dc97e574-ccc5-450a-8cb5-3f86f74820a2.jpg)

OS:Bedrock Linux

**Comment by Grimler91** [comment]
Maybe try adding `no_pivot_root = true` to your podman config, from this thread: https://github.com/containers/podman/issues/2614 (found by searching for the `pivot_root: invalid argument`-error)

Maybe @rojenzaman has a better idea about what issue here is?

**Comment by rojenzaman** [comment]
We must give `--format docker` argument to podman when build. Because  SHELL is not supported for OCI image format. I created a pull request about that.

**Comment by txmu** [comment]
> Maybe try adding `no_pivot_root = true` to your podman config, from this thread: [containers/podman#2614](https://github.com/containers/podman/issues/2614) (found by searching for the `pivot_root: invalid argument`-error)
> 
> Maybe @rojenzaman has a better idea about what issue here is?

This creates new errors
