### ISSUE TITLE
User specific static-dns-hosts.txt file

### ISSUE THREAD

**Issue by lars18th** [termux/termux-docker#44]
Hi,

These containers are very useful. And I have a suggestion to improve them with a small change:
- Change the "update-static-dns" script (`/data/data/com.termux/files/usr/bin/update-static-dns`) to read the list of static hosts from two different locations:
   - The _regular_ location `/system/etc/static-dns-hosts.txt` that represents the common hosts.
   - A new _user_ location like `/data/data/com.termux/static-dns-hosts.txt` that will be left to the user.
   - Or in the location `/system/etc/user-dns-hosts.txt` with zero content (what you prefer).

The idea is to start the docker container with a binding of the _user_ file. Then we don't need to replace the hosts decribed inside the image. And at the same time we can _add_ some other hosts. In my case, for example "kernel.org".

You agree?

**Comment by licy183** [comment]
Great idea! IMO, I also want to improve `update-static-dns` and make it possible to add domains dynamically. If you are willing to do this, feel free to open a PR for that!

PS: I have some final exams these days and may not have much free time for this. I'll start to work on this after Dec 10, which is the last exam I have...

**Comment by lars18th** [comment]
Hi @licy183 ,

I'll prepare then a PR. However, please let me to know what you prefer:
- `/system/etc/user-dns-hosts.txt` (my first idea) or `/data/data/com.termux/static-dns-hosts.txt` to store the user file?

Regards.

**Comment by licy183** [comment]
> 

I'd like to use `/data/data/com.termux/files/home/.static-dns-hosts.txt`. We must edit file permission if we put it under `/system`. I think putting it under user's home will make it easier for us to edit it.

**Comment by lars18th** [comment]
Hi @licy183 ,

PR #45 created. Please check it and merge.

Regards.

**Comment by lars18th** [comment]
I close this issue because the PR is merged.
