### ISSUE TITLE
[possibly not a bug] "mpv": library "libOpenSLES.so" not found

### ISSUE THREAD

**Issue by robertkirkman** [termux/termux-docker#70]
- simple form of error (pure termux-docker):

```
CANNOT LINK EXECUTABLE "mpv": library "libOpenSLES.so" not found
linker: CANNOT LINK EXECUTABLE "mpv": library "libOpenSLES.so" not found
```

- reproduction steps for simple form:

```bash
docker run -it termux/termux-docker:aarch64
yes | pkg upgrade -y
pkg install -y libexpat
pkg install -y mpv
mpv
```

- extended form of error (attempt to install `libOpenSLES.so` into termux-docker by combining redroid image into termux-docker image)

```
● Video  --vid=1               (av1 480x360 30 fps) [default]
● Audio  --aid=1  --alang=eng  (opus 2ch 48000 Hz) [default]
[vo/x11] Warning: this legacy VO has bad performance. Consider fixing your graphics drivers, or not forcing the x11 VO.
Binder driver could not be opened.  Terminating.
libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 6859 (mpv), pid 6859 (mpv)
Aborted (core dumped)
```

- reproduction steps for extended form:

```bash
mkdir termux-docker-redroid-fusion
cd termux-docker-redroid-fusion
FUSION_ROOTFS=$(pwd)
docker export $(docker create termux/termux-docker:aarch64) --output="termux-docker.tar"
docker export $(docker create redroid/redroid:9.0.0-latest) --output="redroid.tar"
tar -xvf "$FUSION_ROOTFS/termux-docker.tar"
docker run -it --rm \
    -v "$FUSION_ROOTFS"/system:/system \
    -v "$FUSION_ROOTFS":/mnt/rootfs \
    debian \
    bash -c 'tar -h --skip-old-files  -C / -xvf /mnt/rootfs/redroid.tar'
docker run -it -p 5900:5900 \
    -v "$FUSION_ROOTFS"/system:/system \
     --ulimit nofile=1048576:1048576 \
    termux/termux-docker:aarch64
export TERM=xterm
yes | pkg upgrade -y
pkg install -y x11-repo tur-repo
pkg install -y libexpat
pkg install -y tigervnc x11vnc xfce mpv-x
pip install yt-dlp
yt-dlp https://www.youtube.com/watch?v=FtutLA63Cp8 -o "video.%(ext)s"
vncserver :1 -xstartup xfce4-session 
export DISPLAY=:1
x11vnc -noshm &
mpv video*
```

Continuation of #27 

Continuation of https://github.com/remote-android/redroid-doc/issues/705

termux-docker can already run some packages, but because Termux and other Android apps have very permissive and easily compatible access, much more than most other APIs, to **system OpenSLES**, through the `openal-soft`  package, we have a practice of sometimes building our packages depending on this, so if this depends also on Binder, it may also be necessary to install Binder, or more components, before all termux packages could run in termux-docker.

redroid supports "OpenSLES" and "Binder" , so when Termux App is installed inside a complete redroid container, these errors do not happen. The downside of that is that it takes too long to load and also too intensive to run especially on slow computers.

The goal of the idea is, trying to make termux-docker able to run official termux packages so it could be used as automated integration testing of binaries from the CI of termux-packages. It would not be necessary to get sound to actually play audibly, it would just be necessary to get a return code from each program in a basic functionality test, that matches the return code from the same build of the package on normal Android devices, without modifying the build.

The optimistic hope is that it might not be required to completely install and launch SurfaceFlinger in order to activate OpenSLES. If it is required to completely install and launch SurfaceFlinger in order to activate OpenSLES, then this would mean the entire Redroid has to be installed and there is no benefit to trying to create an "in between mixture" of termux-docker and redroid.

In the future I will next try merging other components like merging the docker entrypoints of redroid and termux-docker together to see if it would be possible to open a Termux Bash shell directly through `docker run` on a redroid image, then remove components from redroid until all components have been removed that are not necessary for Termux packages.

**Comment by Biswa96** [comment]
The readme already says "Environment doesn't have Android runtime components, so certain things will not be available (DalvikVM, OpenSLES, etc...)."

termux-docker is not used as an alternative of Android Virtual Device.

**Comment by robertkirkman** [comment]
Yes, I am very sorry to bother you since I know about how the README says it is not supposed to work, but, very luckily, I have found a project that directly helps this problem.
Before installing this, apps would find no `libOpenSLES.so` and crash, 
or find the redroid `libOpenSLES.so` I tried to install, which has a problem, and crash,
but after I wrote and installed this package, which compiles source code I found in
https://gitlab.com/android_translation_layer/,
apps are able to load this custom build of `libOpenSLES.so` and do not crash, instead they
get a handled error and are able to ignore the error, disable audio dynamically and continue running!

Since it turns out it is possible to do something like this to slightly work around this type of problem,
despite the lack of most of the Android Virtual Device components,
I believe it might be very useful for someone someday, and I believe if there are any other similar
crashes that happen with termux packages in termux-docker but not in the normal Termux App, 
it might be possible to work around those too one day.


<details>
<summary>libopensles-standalone package full commands</summary>

```
git clone https://github.com/termux/termux-packages.git
cd termux-packages/
git apply -v << 'EOF'
--- /dev/null
+++ b/packages/libopensles-standalone/build.sh
@@ -0,0 +1,27 @@
+TERMUX_PKG_HOMEPAGE="https://gitlab.com/android_translation_layer/libopensles-standalone"
+TERMUX_PKG_DESCRIPTION="Fork of google's libOpenSLES implementation"
+TERMUX_PKG_LICENSE="Apache-2.0"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION=2024.02.21
+_COMMIT=605a83f47263a022427afb6e95801bd39b459b78
+TERMUX_PKG_SRCURL=git+https://gitlab.com/android_translation_layer/libopensles-standalone.git
+TERMUX_PKG_GIT_BRANCH=known_working_desktop_build
+TERMUX_PKG_SHA256=b7a37877edf84dab8bcbb74eba13add5698763136f62718e31008be55e832779
+TERMUX_PKG_DEPENDS="sdl2, libsndfile"
+
+termux_step_post_get_source() {
+	git fetch --unshallow
+	git checkout $_COMMIT
+
+	local version="$(git log -1 --format=%cs | sed 's/-/./g')"
+	if [ "$version" != "$TERMUX_PKG_VERSION" ]; then
+		echo -n "ERROR: The specified version \"$TERMUX_PKG_VERSION\""
+		echo " is different from what is expected to be: \"$version\""
+		exit 1
+	fi
+
+	local s=$(find . -type f ! -path '*/.git/*' -print0 | xargs -0 sha256sum | LC_ALL=C sort | sha256sum)
+	if [[ "${s}" != "${TERMUX_PKG_SHA256}  "* ]]; then
+		termux_error_exit "Checksum mismatch for source files."
+	fi
+}
\ No newline at end of file
--- /dev/null
+++ b/packages/libopensles-standalone/remove-jni-dependency.patch
@@ -0,0 +1,18 @@
+--- a/meson.build
++++ b/meson.build
+@@ -1,5 +1,4 @@
+-project('libopensles', ['c', 'java'])
+-# java somehow needed for jni
++project('libopensles', ['c'])
+ 
+ incdir_dep = declare_dependency(include_directories: 'include')
+ add_project_dependencies(incdir_dep, language: 'c')
+@@ -16,7 +15,7 @@ libopensles = shared_library(
+ 	],
+ 	gnu_symbol_visibility: 'hidden',
+ 	dependencies: [
+-		dependency('dl'), dependency('jni'), libm_dep, dependency('threads'), dependency('sdl2'), dependency('sndfile'),
++		dependency('dl'), libm_dep, dependency('threads'), dependency('sdl2'), dependency('sndfile'),
+ 	],
+ 	link_with: [
+ 		opensles_util, opensles_helper
EOF
scripts/setup-termux.sh
./build-package.sh -I -f libopensles-standalone
cd output
pkg install ./*.deb
```

</details>

I know that this package is of course not a good fit for the official repository, because it really doesn't do anything, it's just a workaround for termux-docker specifically. I just think it might be useful for anyone having the same error.

![image](https://github.com/user-attachments/assets/5e910c97-80b8-48ce-a42f-22781a036c37)

**Comment by robertkirkman** [comment]
After they have been merged, these two PRs will automatically combine into each other and cause this issue to be actually fixed by default (auto enabling working video-only mode with no crash in `luanti` and `mpv-x` within termux-docker):

- #72 
- https://github.com/termux/termux-packages/pull/23712
