### ISSUE TITLE
failed to run clang --help or anything to do with clang..

### ISSUE THREAD

**Issue by John4650-hub** [termux/termux-docker#71]
After installing clang on the container i get
```bash
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/clang": cannot locate symbol "_ZNSt6__ndk122__libcpp_verbose_abortEPKcz" referenced by "/data/data/com.termux/files/usr/bin/clang-19"...
```
I ran pkg update && pkg upgrade first, the error still persists.

**Comment by sylirre** [comment]
Please tell how did you set up the container and how clang was installed.

I can't reproduce the issue on i686, x86_64 image variants.

**Comment by John4650-hub** [comment]
The container started but the following information was displayed
```bash
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
error getting old personality value: Operation not permitted
libc: error getting old personality value: Operation not permitted
Aborted (core dumped)
[!] Container is running as non-root, unable to start dnsmasq. DNS will be unavailable.
error getting old personality value: Operation not permitted
libc: error getting old personality value: Operation not permitted
```
The `Run Termux` step won't proceed as the container doesn't stop.
This how the workflow step looks like
```yaml
- name: Run Termux
      run: |
        docker run --rm --privileged aptman/qus -s -- -p aarch64 arm
        docker run --rm termux/termux-docker:arm bash -c "apt update && apt install -yq clang && clang -help > foo.txt"
        docker ps -q | xargs -r docker stop

    - name: Show foo
      run: cat foo.txt
```

_Originally posted by @John4650-hub in https://github.com/termux/termux-app/discussions/4291#discussioncomment-11506467_

**Comment by John4650-hub** [comment]
> Please tell how did you set up the container and how clang was installed.
> 
> I can't reproduce the issue on i686, x86_64 image variants.

## Here is the step in workflow
```yml
- name: Set up QEMU for aarch64 emulation
  run: docker run --rm --privileged aptman/qus -s -- -p aarch64 arm

- name: Run Termux
  run: |
     docker run \
      --privileged \
      --name termux-docker-arm \
      -v "${{ github.workspace }}/install_deps.sh:/scripts/install_deps.sh" \
      termux/termux-docker:arm \
      bash -c "bash /scripts/install_deps.sh"
      docker stop termux-docker-arm
```
The code in `install_deps.sh` is as below
```bash
#!/bin/bash

pkg update && pkg upgrade
pkg install -yq clang
pkg install -y python3

clang --help
```

**Comment by John4650-hub** [comment]
@sylirre that's just it

**Comment by sylirre** [comment]
I managed to reproduce your issue locally but there is no problem on the side of termux-docker. It is a bug in your script.

`pkg update && pkg upgrade` - this caused package manager to update index but not to perform actual package upgrade.

`pkg` is a wrapper for `apt`, the latter by default expects interactive shell. Your command will not work on GitHub Actions properly and subsequent `pkg install` command will cause a *partial upgrade* condition which is not supported by Termux design.

Usually for non-interactive usage of package manager following should be used instead:

Variant 1:
```
env DEBIAN_FRONTEND=noninteractive pkg upgrade -yq
```

Variant 2, will answer "yes" to all configuration file update prompts (recommended):
```
yes | pkg upgrade -q
```
