### ISSUE TITLE
Support arm and aarch64 containers

### ISSUE THREAD

**Issue by umarcor** [termux/termux-docker#9]
The current content of `system` is for x64_64, so it fails when trying to use the dockerfile in this repo on ARM. See https://github.com/umarcor/termux-docker/runs/1898880670?check_suite_focus=true#step:4:3402: `/system/bin/linker64: Invalid ELF image for this architecture`.

Is it possible to provide `system` subdir variants for ARM?

**Comment by xeffyr** [comment]
Support of arm/aarch64 containers is now added.

However ARM variant has issues, as require a custom seccomp profile to remove restrictions from `personality()` system call used during libc initialization.
